apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-email-service
  labels:
    app: ecommerce-email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-email-service
  template:
    metadata:
      labels:
        app: ecommerce-email-service
    spec:
      containers:
        - name: ecommerce-email-service
          image: ghcr.io/jamess-lucass/ecommerce-email-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 200Mi
              cpu: 100m
