apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-email-service-mailhog
  labels:
    app: ecommerce-email-service-mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-email-service-mailhog
  template:
    metadata:
      labels:
        app: ecommerce-email-service-mailhog
    spec:
      containers:
        - name: ecommerce-email-service-mailhog
          image: mailhog/mailhog:latest
          imagePullPolicy: Always
          ports:
            - name: smtp
              containerPort: 1025
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 200m
---
kind: Service
apiVersion: v1
metadata:
  name: ecommerce-email-service-mailhog
spec:
  selector:
    app: ecommerce-email-service-mailhog
  ports:
    - protocol: TCP
      targetPort: 1025
      port: 80
