kind: Service
apiVersion: v1
metadata:
  name: ecommerce-email-service-service
spec:
  selector:
    app: ecommerce-email-service-deployment
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 80
