apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-email-service
spec:
  template:
    spec:
      containers:
        - name: ecommerce-email-service
          env:
            - name: RABBITMQ_HOST
              value: "rabbit-mq.default.svc"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbit-mq-default-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbit-mq-default-user
                  key: password
            - name: SMTP_HOST
              value: "ecommerce-email-service-mailhog.default.svc"
            - name: SMTP_PORT
              value: "1025"
